import './globals.css';
import '@/css/main.css';
import type { Metadata } from 'next';
import { Montserrat, Nunito } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  style: 'normal',
  variable: '--font-montserrat',
});
const nunito = Nunito({
  subsets: ['latin'],
  style: 'normal',
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log({ montserrat });

  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${nunito.variable} body`}>
        {children}
      </body>
    </html>
  );
}
