import './globals.css'
import '@/css/main.css'
import type { Metadata } from 'next'
import { Montserrat,Nunito } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] ,style:'normal',variable:'--font-montserrat'})
const nunito = Nunito({ subsets: ['latin'],style:'normal',variable:'--font-nunito' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} body ${nunito.variable} body`}>{children}</body>
    </html>
  )
}
